# Site settings
title: Events Portfolio
description: Portfolio of select events I organized
keywords: portfolio, events
author: Jacek Jonca-Jasinski
baseurl: "/events/" # the subpath of your site, e.g. /blog/
url: "https://jonca.org" # the base hostname & protocol for your site
